### PR TITLE
published to npm

### PR DESCRIPTION
**Pull request by rofrol**

### CODE REVIEW

**Comment by stylemistake** [comment]
Wow, I like your idea with publishing it to npm, but I'm not sure if I can pull this to master.

* You changed a lot of the code, big chunk of changes was really unnecessary. Iit was working perfectly fine, why changing? (btw, `runner_pretty_s` doesn't work for me)
* Why should we support bash versions less than v4? It was released in 2009, all modern distros have it already.
* Package version should not be 1.0. The script is not out of alpha yet and will probably change a lot over time. You should really consider removing it from npm to avoid confusion.

**Comment by stylemistake** [comment]
I've looked up some info, and it seems that you are using OS X. It does indeed has a bash v3 and a different `date` utility, which doesn't support nanoseconds. I'll create issues for that.

**Comment by rofrol** [comment]
I'm using git bash on windows, that's why I need bash 3.

I think that we can also use bash-require for colors

https://github.com/bashinate/bash-require

**Comment by rofrol** [comment]
Right, my mistake. I wanted to add my project https://github.com/rofrol/react-starter-kit

**Pull request closed without merging**
