### PR TITLE
Add "runner_run" function

### PR DESCRIPTION
**Pull request by mbrodala**
This function can be used to wrap arbitrary commands which will be outputted before execution.

### CODE REVIEW

**Comment by stylemistake** [comment]
Why would you need to see the commands executing?

**Comment by mbrodala** [comment]
Right now one has to make sure to log useful messages, otherwise nothing can be seen in the output except the start/end message when running tasks. Thus the idea was to give users a way to run commands and have them outputted, e.g. for reliable logging in CI environments.

Example `Runnerfile.sh`:

```shell
task_install() {
  composer install
}
```

Executing `runner install` will now only output this:

```
[12:17:20.271] Starting 'install'...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
[12:17:20.883] Finished 'install' after 609 ms
```

It's impossible to see what command exactly was run to achieve this output. Slightly changed `Runnerfile.sh`:

```shell
task_install() {
  runner_run composer install
}
```

Output now:

```
[12:19:17.170] Starting 'install'...
[12:19:17.173] composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
[12:19:17.932] Finished 'install' after 758 ms
```

A very basic example but you should get the idea.

And yes, I'd also love to simply write plain commands and still have them outputted.

**Comment by stylemistake** [comment]
Could you rebase this onto the master? It would then be a fast forward instead of the merge.

**Comment by mbrodala** [comment]
Alright, done.

**Comment by mbrodala** [comment]
Thanks. :-)

**Pull request merged**
